name: "CI"
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    name: "[${{matrix.otp}}/${{matrix.elixir}}] CI Tests on ExConductor [OTP/Elixir]"
        strategy:
          fail-fast: false
          matrix:
            otp: [22.2, 23]
            elixir: [1.12]
        steps:
          - uses: actions/checkout@v2.3.1
            with:
              fetch-depth: 0
          - uses: erlef/setup-beam@v1
            with:
              otp-version: ${{matrix.otp}}
              elixir-version: ${{matrix.elixir}}
          - run: mix deps.get
          - run: mix deps.compile
          - run: mix compile --warnings-as-errors
          - run: mix test
